import type { CalendarEvent } from "@/types/calendar";

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: "evt-1",
    day: 3,
    month: 8,
    year: 2026,
    title: "Meeting A",
    startTime: "10:00",
    endTime: "11:30",
    category: "Meeting",
    desc: "Sprint cadence & sprint grooming with team",
    colorBg: "bg-[#D3E5FA]",
    colorText: "text-[#1D4ED8]",
    colorBorder: "border-blue-200",
    overflowCount: 2,
  },
  {
    id: "evt-2",
    day: 7,
    month: 8,
    year: 2026,
    title: "All-Day Project Sprint",
    startTime: "00:00",
    endTime: "23:59",
    category: "Launch",
    desc: "ProLens Core release final sprint marathon",
    colorBg: "bg-[#FECDD3]",
    colorText: "text-[#9F1239]",
    colorBorder: "border-rose-200",
    overflowCount: 0,
  },
  {
    id: "evt-3",
    day: 9,
    month: 8,
    year: 2026,
    title: "International Client Call",
    startTime: "03:00",
    endTime: "04:00",
    category: "Client",
    desc: "APAC Sync and status demonstration",
    colorBg: "bg-[#C2F3D2]",
    colorText: "text-[#15803D]",
    colorBorder: "border-emerald-200",
    overflowCount: 1,
  },
  {
    id: "evt-4",
    day: 10,
    month: 8,
    year: 2026,
    title: "Workshop A",
    startTime: "14:00",
    endTime: "16:00",
    category: "Workshop",
    desc: "Architecture patterns & modular tailwind components",
    colorBg: "bg-[#E9D5FF]",
    colorText: "text-[#6B21A8]",
    colorBorder: "border-purple-200",
    overflowCount: 2,
  },
  {
    id: "evt-5",
    day: 11,
    month: 8,
    year: 2026,
    title: "Ads Campaign Nr2",
    startTime: "09:00",
    endTime: "18:00",
    category: "Marketing",
    desc: "AdSense + FB, Target A...",
    colorBg: "bg-[#FCEEA7]",
    colorText: "text-[#854D0E]",
    colorBorder: "border-amber-200",
    overflowCount: 0,
  },
  {
    id: "evt-6",
    day: 12,
    month: 8,
    year: 2026,
    title: "Ads Campaign Nr2",
    startTime: "09:00",
    endTime: "18:00",
    category: "Marketing",
    desc: "AdSense + FB, Target A...",
    colorBg: "bg-[#FCEEA7]",
    colorText: "text-[#854D0E]",
    colorBorder: "border-amber-200",
    overflowCount: 4,
  },
  {
    id: "evt-7",
    day: 13,
    month: 8,
    year: 2026,
    title: "Ads Campaign Nr2",
    startTime: "09:00",
    endTime: "18:00",
    category: "Marketing",
    desc: "AdSense + FB, Target A...",
    colorBg: "bg-[#FCEEA7]",
    colorText: "text-[#854D0E]",
    colorBorder: "border-amber-200",
    overflowCount: 1,
  },
  {
    id: "evt-8",
    day: 14,
    month: 8,
    year: 2026,
    title: "Ads Campaign Nr2",
    startTime: "09:00",
    endTime: "18:00",
    category: "Marketing",
    desc: "AdSense + FB, Target A...",
    colorBg: "bg-[#FCEEA7]",
    colorText: "text-[#854D0E]",
    colorBorder: "border-amber-200",
    overflowCount: 1,
  },
  {
    id: "evt-9",
    day: 15,
    month: 8,
    year: 2026,
    title: "Ads Campaign Nr2",
    startTime: "09:00",
    endTime: "18:00",
    category: "Marketing",
    desc: "AdSense + FB, Target ...",
    colorBg: "bg-[#FCEEA7]",
    colorText: "text-[#854D0E]",
    colorBorder: "border-amber-200",
    overflowCount: 3,
  },
  {
    id: "evt-10",
    day: 17,
    month: 8,
    year: 2026,
    title: "Team Breakfast",
    startTime: "07:00",
    endTime: "08:30",
    category: "Meeting",
    desc: "Quarterly team celebration breakfast",
    colorBg: "bg-[#D3E5FA]",
    colorText: "text-[#1D4ED8]",
    colorBorder: "border-blue-200",
    overflowCount: 0,
  },
  {
    id: "evt-11",
    day: 19,
    month: 8,
    year: 2026,
    title: "Asia Market Review",
    startTime: "01:00",
    endTime: "03:00",
    category: "Client",
    desc: "Quarterly review with Singapore partners",
    colorBg: "bg-[#C2F3D2]",
    colorText: "text-[#15803D]",
    colorBorder: "border-emerald-200",
    overflowCount: 5,
  },
  {
    id: "evt-12",
    day: 20,
    month: 8,
    year: 2026,
    title: "Early Strategy Meeting",
    startTime: "02:00",
    endTime: "04:00",
    category: "Workshop",
    desc: "Executive roadmap planning",
    colorBg: "bg-[#E9D5FF]",
    colorText: "text-[#6B21A8]",
    colorBorder: "border-purple-200",
    overflowCount: 3,
  },
  {
    id: "evt-13",
    day: 22,
    month: 8,
    year: 2026,
    title: "Product Launch",
    startTime: "10:00",
    endTime: "12:00",
    category: "Launch",
    desc: "Public roll-out of WorkFlow v2.4",
    colorBg: "bg-[#FECDD3]",
    colorText: "text-[#9F1239]",
    colorBorder: "border-rose-200",
    overflowCount: 1,
  },
  {
    id: "evt-14",
    day: 24,
    month: 8,
    year: 2026,
    title: "Conference A",
    startTime: "13:00",
    endTime: "15:00",
    category: "Client",
    desc: "Keynote delivery and panel session",
    colorBg: "bg-[#C2F3D2]",
    colorText: "text-[#15803D]",
    colorBorder: "border-emerald-200",
    overflowCount: 2,
  },
  {
    id: "evt-15",
    day: 25,
    month: 8,
    year: 2026,
    title: "Training Session",
    startTime: "14:00",
    endTime: "17:00",
    category: "Workshop",
    desc: "Security standard training for all engineering staff",
    colorBg: "bg-[#E9D5FF]",
    colorText: "text-[#6B21A8]",
    colorBorder: "border-purple-200",
    overflowCount: 0,
  },
  {
    id: "evt-16",
    day: 28,
    month: 8,
    year: 2026,
    title: "Board Meeting",
    startTime: "15:00",
    endTime: "17:00",
    category: "Meeting",
    desc: "Q3 Board of Directors strategic approval",
    colorBg: "bg-[#D3E5FA]",
    colorText: "text-[#1D4ED8]",
    colorBorder: "border-blue-200",
    overflowCount: 2,
  },
];

export const CATEGORY_COLOR_MAP: Record<
  string,
  { bg: string; text: string; border: string }
> = {
  Meeting: {
    bg: "bg-[#D3E5FA]",
    text: "text-[#1D4ED8]",
    border: "border-blue-200",
  },
  Client: {
    bg: "bg-[#C2F3D2]",
    text: "text-[#15803D]",
    border: "border-emerald-200",
  },
  Workshop: {
    bg: "bg-[#E9D5FF]",
    text: "text-[#6B21A8]",
    border: "border-purple-200",
  },
  Marketing: {
    bg: "bg-[#FCEEA7]",
    text: "text-[#854D0E]",
    border: "border-amber-200",
  },
  Launch: {
    bg: "bg-[#FECDD3]",
    text: "text-[#9F1239]",
    border: "border-rose-200",
  },
};
