import type { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    name: "Website Redesign",
    client: "Acme Corporation",
    description:
      "Next-gen WCAG AAA enterprise overhaul, headless CMS decoupling, and design token integration.",
    status: "ongoing",
    lead: "Sarah Jenkins",
    activeSprint: "Sprint 4: Active",
    dateRange: "Sep 1 – Nov 30, 2026",
    dueDate: "Nov 30, 2026",
    completionPercentage: 68,
    estimatedHours: 240,
    loggedHours: 163,
    tasksCount: 8,
    coreFeaturesCount: 4,
    pendingInvites: [
      {
        id: "inv-1",
        email: "kai.rodriguez@tarento.com",
        role: "employee",
        expiresInDays: 5,
      },
      {
        id: "inv-2",
        email: "sophie.muller@contractor.io",
        role: "employee",
        expiresInDays: 7,
      },
    ],
    members: [
      {
        id: "mem-1",
        name: "Alex Morgan",
        email: "alex.morgan@tarento.com",
        initials: "AM",
        role: "manager",
        designation: "Lead Architect & PM",
        assignedTasksCount: 5,
        assignedFeaturesCount: 2,
        hoursLogged: 46.5,
        status: "active",
      },
      {
        id: "mem-2",
        name: "Elena Rostova",
        email: "elena.rostova@tarento.com",
        initials: "ER",
        role: "employee",
        designation: "Senior Fullstack Engineer",
        assignedTasksCount: 6,
        assignedFeaturesCount: 2,
        hoursLogged: 42.0,
        status: "active",
      },
      {
        id: "mem-3",
        name: "Marcus Chen",
        email: "marcus.chen@tarento.com",
        initials: "MC",
        role: "employee",
        designation: "Staff Frontend Engineer",
        assignedTasksCount: 4,
        assignedFeaturesCount: 1,
        hoursLogged: 37.5,
        status: "active",
      },
      {
        id: "mem-4",
        name: "Sarah Jenkins",
        email: "sarah.j@tarento.com",
        initials: "SJ",
        role: "employee",
        designation: "Lead Product Designer",
        assignedTasksCount: 3,
        assignedFeaturesCount: 1,
        hoursLogged: 24.0,
        status: "active",
      },
      {
        id: "mem-5",
        name: "David Kim",
        email: "david.kim@tarento.com",
        initials: "DK",
        role: "employee",
        designation: "QA Automation Lead",
        assignedTasksCount: 4,
        assignedFeaturesCount: 1,
        hoursLogged: 13.0,
        status: "active",
      },
    ],
  },
  {
    id: "proj-2",
    name: "Mobile App v2.0",
    client: "FinTech Labs",
    description:
      "Cross-platform migration, biometrics authentication, and automated expense reporting module.",
    status: "ongoing",
    lead: "Alex Morgan",
    activeSprint: "Sprint 2: Active",
    dateRange: "Oct 1 – Dec 15, 2026",
    dueDate: "Dec 15, 2026",
    completionPercentage: 42,
    estimatedHours: 320,
    loggedHours: 134,
    tasksCount: 14,
    coreFeaturesCount: 6,
    pendingInvites: [],
    members: [
      {
        id: "mem-1",
        name: "Alex Morgan",
        email: "alex.morgan@tarento.com",
        initials: "AM",
        role: "manager",
        designation: "Lead Architect & PM",
        assignedTasksCount: 7,
        assignedFeaturesCount: 3,
        hoursLogged: 60.0,
        status: "active",
      },
      {
        id: "mem-3",
        name: "Marcus Chen",
        email: "marcus.chen@tarento.com",
        initials: "MC",
        role: "employee",
        designation: "Staff Frontend Engineer",
        assignedTasksCount: 7,
        assignedFeaturesCount: 3,
        hoursLogged: 74.0,
        status: "active",
      },
    ],
  },
  {
    id: "proj-3",
    name: "Cloud Migration",
    client: "Helios Systems",
    description:
      "Legacy on-prem DB migration to multi-region cloud cluster with zero-downtime cutover.",
    status: "pending",
    lead: "David Kim",
    activeSprint: "Planning Phase",
    dateRange: "Jan 10 – Mar 30, 2027",
    dueDate: "Q1 2027",
    completionPercentage: 10,
    estimatedHours: 180,
    loggedHours: 18,
    tasksCount: 5,
    coreFeaturesCount: 3,
    pendingInvites: [],
    members: [
      {
        id: "mem-5",
        name: "David Kim",
        email: "david.kim@tarento.com",
        initials: "DK",
        role: "employee",
        designation: "QA Automation Lead",
        assignedTasksCount: 5,
        assignedFeaturesCount: 3,
        hoursLogged: 18.0,
        status: "active",
      },
    ],
  },
];
